name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pylint:
    name: PyLint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install
        run: |
          python3 -m pip install -U -r requirements.txt
      - name: Run
        run: |
          echo -e "\n\`\`\`\n" >> $GITHUB_STEP_SUMMARY
          pylint --ignore="=~,__pycache__,venv,.mypy_cache" . >> $GITHUB_STEP_SUMMARY
          echo -e "\n\`\`\`\n" >> $GITHUB_STEP_SUMMARY
  mypy:
    name: MyPy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install
      run: |
        python3 -m pip install -U -r requirements.txt
    - name: Run
      run: |
        echo -e "\n\`\`\`\n" >> $GITHUB_STEP_SUMMARY
        mypy >> $GITHUB_STEP_SUMMARY
        echo -e "\n\`\`\`\n" >> $GITHUB_STEP_SUMMARY
