name: Docs

on:
  push:
    branches:
      - main

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    name: Generate Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install
        run: |
          python3 -m pip install -U -r requirements.txt
      - name: Update Diagrams
        run: |
          python3 pypu.py -m ./ -f svg > ./example.svg
          python3 pypu.py -m ./data/ -f svg > ./data/uml.svg
          python3 pypu.py -m ./utils/ -f svg > ./utils/uml.svg
      - name: PDoc
        run: pdoc pypu.py utils data --favicon https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/code/default/48px.svg --logo https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/code/default/48px.svg -o ./docs
      - name: Upload PDoc
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/
  deploy:
    name: Deploy Documentation
    needs: generate
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
